# --- IMPORTS ---
import os
import tempfile
import requests
import traceback
from contextlib import asynccontextmanager
from fastapi import FastAPI, HTTPException
from fastapi.responses import PlainTextResponse
from pydantic import BaseModel, Field
from typing import List, Dict, Literal
from urllib.parse import urlparse

# --- WORKER IMPORTS ---
# Import the high-level functions and initializers from your worker script.
from worker import (
    load_environment_config,
    initialize_services,
    generate_document_id,
    process_and_index_pdf,
    process_and_index_docx,
    process_and_index_url,
    process_and_index_pptx,
    process_and_index_excel,
    process_and_index_image,
    process_and_index_zip,
    answer_queries,
    analyze_legal_risks,
    PROCESSED_DOCS_KEY, # Import for the Redis check
    RAG_CONFIG # Import the new config dictionary
)

# --- LIFESPAN MANAGEMENT & GLOBAL SERVICES ---
# This dictionary will hold our initialized services (clients, models, etc.)
services: Dict = {}

@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Handles startup and shutdown events for the FastAPI application.
    Initializes all necessary services on startup.
    """
    print("🚀 API starting up...")
    print("Loading environment configuration...")
    config = load_environment_config()
    print("Initializing all services (DB, AI Models, etc.)...")
    services.update(initialize_services(config))
    print("✅ Services initialized. API is ready.")
    yield
    print("👋 API shutting down...")
    services.clear()

app = FastAPI(
    title="DeepRead AI - Legal Risk Detection API",
    description="AI-powered legal risk detection system for sponsorship agreements. Also supports general RAG Q&A.",
    version="2.0.0",
    lifespan=lifespan
)

# --- Pydantic Models ---

# This is the corrected code
class JobRequest(BaseModel):
    documents: str = Field(..., description="A URL pointing to the document (PDF, DOCX, or HTML page) to be processed.")
    questions: List[str] = Field(..., description="A list of questions to be answered based on the document.")
    semantic_weight: float = Field(RAG_CONFIG["semantic_weight"], description="The weight for semantic search results.")
    keyword_weight: float = Field(RAG_CONFIG["keyword_weight"], description="The weight for keyword search results.")
    k_semantic: int = Field(RAG_CONFIG["k_semantic"], description="Number of candidates for semantic search.")
    k_keyword: int = Field(RAG_CONFIG["k_keyword"], description="Number of candidates for keyword search.")
    k_rerank: int = Field(RAG_CONFIG["k_rerank"], description="Number of final contexts to use after reranking.")


class JobResponse(BaseModel):
    """Defines the structure for the API's successful response."""
    job_id: str = Field(..., description="The unique identifier for the processing job, derived from the document source.")
    answers: List[str] = Field(..., description="A list of answers generated by the RAG pipeline, corresponding to the input questions.")


# --- Legal Risk Detection Models ---

class AnalyzeRequest(BaseModel):
    """Request model for the legal risk detection endpoint."""
    document: str = Field(..., description="A URL pointing to the sponsorship agreement document (PDF, DOCX, etc.).")
    format: Literal["json", "text"] = Field("text", description="Output format: 'text' for human-readable report, 'json' for structured JSON.")
    semantic_weight: float = Field(RAG_CONFIG["semantic_weight"], description="The weight for semantic search results.")
    keyword_weight: float = Field(RAG_CONFIG["keyword_weight"], description="The weight for keyword search results.")
    k_semantic: int = Field(RAG_CONFIG["k_semantic"], description="Number of candidates for semantic search.")
    k_keyword: int = Field(RAG_CONFIG["k_keyword"], description="Number of candidates for keyword search.")
    k_rerank: int = Field(RAG_CONFIG["k_rerank"], description="Number of final contexts to use after reranking.")


class RiskyClause(BaseModel):
    """A single risky clause detected in the document."""
    clause_text: str = Field(..., description="The exact or near-exact text of the risky clause from the contract.")
    risk_categories: List[str] = Field(..., description="List of risk category keys this clause belongs to (e.g., ['termination', 'liability']).")
    risk_level: str = Field(..., description="Risk severity: high, medium, or low.")
    explanation: str = Field(..., description="Why this clause is risky or potentially harmful.")
    recommendation: str = Field(..., description="Actionable suggestion to mitigate the risk.")


class AnalyzeResponse(BaseModel):
    """Response model for legal risk detection."""
    document_id: str = Field(..., description="The unique identifier for the analyzed document.")
    total_risks_found: int = Field(..., description="Total number of risky clauses detected.")
    high_risk_count: int = Field(..., description="Number of high-risk clauses.")
    medium_risk_count: int = Field(..., description="Number of medium-risk clauses.")
    low_risk_count: int = Field(..., description="Number of low-risk clauses.")
    risky_clauses: List[RiskyClause] = Field(..., description="List of all detected risky clauses, sorted by severity.")


def format_risk_report(data: AnalyzeResponse) -> str:
    """Formats the risk analysis response into a clean, human-readable plain-text report."""
    separator = "=" * 70
    thin_sep = "-" * 70

    lines = [
        separator,
        "  LEGAL RISK ANALYSIS REPORT",
        separator,
        "",
        f"  Document ID    : {data.document_id}",
        f"  Total Risks    : {data.total_risks_found}",
        "",
        f"  HIGH Risk      : {data.high_risk_count}",
        f"  MEDIUM Risk    : {data.medium_risk_count}",
        f"  LOW Risk       : {data.low_risk_count}",
        "",
        separator,
        "  DETAILED FINDINGS",
        separator,
    ]

    for i, clause in enumerate(data.risky_clauses, 1):
        risk_badge = f"[{clause.risk_level.upper()}]"
        categories_str = ", ".join(clause.risk_categories)
        lines.append("")
        lines.append(f"  Clause {i}  {risk_badge}")
        lines.append(f"  {thin_sep}")
        lines.append(f"  Categories     : {categories_str}")
        lines.append(f"  Risk Level     : {clause.risk_level.upper()}")
        lines.append(f"")
        lines.append(f"  Clause Text:")
        # Word-wrap the clause text for readability
        for wrapped_line in _wrap_text(clause.clause_text, 64):
            lines.append(f"    \"{wrapped_line}\"")
        lines.append(f"")
        lines.append(f"  Why It's Risky:")
        for wrapped_line in _wrap_text(clause.explanation, 64):
            lines.append(f"    {wrapped_line}")
        lines.append(f"")
        lines.append(f"  Recommendation:")
        for wrapped_line in _wrap_text(clause.recommendation, 64):
            lines.append(f"    {wrapped_line}")
        lines.append("")

    lines.append(separator)
    lines.append("  END OF REPORT")
    lines.append(separator)
    return "\n".join(lines)


def _wrap_text(text: str, width: int) -> List[str]:
    """Simple word-wrap utility."""
    words = text.split()
    wrapped_lines = []
    current_line = ""
    for word in words:
        if current_line and len(current_line) + 1 + len(word) > width:
            wrapped_lines.append(current_line)
            current_line = word
        else:
            current_line = f"{current_line} {word}".strip()
    if current_line:
        wrapped_lines.append(current_line)
    return wrapped_lines


# --- Internal Helpers ---

async def _ingest_document_if_needed(document_url: str, document_id: str):
    """Downloads and indexes a document if it hasn't been processed yet."""
    if services["redis_conn"].sismember(PROCESSED_DOCS_KEY, document_id):
        print(f"\u2705 Document ID '{document_id}' found in cache. Skipping indexing.")
        return

    temp_file_path = None
    try:
        url_path = urlparse(document_url).path
        file_extension = os.path.splitext(url_path)[-1].lower()

        if file_extension in [".pdf", ".docx", ".pptx", ".xlsx", ".xls", ".jpg", ".jpeg", ".png", ".zip"]:
            print(f"\u2705 Detected '{file_extension}' from URL. Attempting to download file...")
            response = requests.get(document_url, timeout=30)
            response.raise_for_status()
            with tempfile.NamedTemporaryFile(delete=False, suffix=file_extension) as temp_file:
                temp_file.write(response.content)
                temp_file_path = temp_file.name
            if file_extension == ".pdf": await process_and_index_pdf(temp_file_path, document_id, services)
            elif file_extension == ".docx": await process_and_index_docx(temp_file_path, document_id, services)
            elif file_extension == ".pptx": await process_and_index_pptx(temp_file_path, document_id, services)
            elif file_extension in ['.xlsx', '.xls']: await process_and_index_excel(temp_file_path, document_id, services)
            elif file_extension in ['.jpg', '.jpeg', '.png']: await process_and_index_image(temp_file_path, document_id, services)
            elif file_extension == ".zip": await process_and_index_zip(temp_file_path, document_id, services)
        else:
            print(f"\u26a0\ufe0f No specific file extension detected. Assuming it is a webpage to scrape...")
            await process_and_index_url(document_url, document_id, services)
    except Exception as e:
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=f"Failed to process document: {str(e)}")
    finally:
        if temp_file_path: os.unlink(temp_file_path)


# --- API Endpoints ---

@app.post('/hackrx/run', response_model=JobResponse)
async def process_job(request: JobRequest):
    """
    Processes a document, answers questions about it, and returns the results.
    This endpoint handles document indexing (if new) and the full RAG pipeline.
    """
    document_url = request.documents
    document_id = generate_document_id(document_url)

    # --- STAGE 1: DOCUMENT PROCESSING & INDEXING ---
    await _ingest_document_if_needed(document_url, document_id)

    # --- STAGE 2: QUESTION ANSWERING ---
    try:
        print(f"🤖 Starting Q&A pipeline for {len(request.questions)} questions...")
        # [cite_start]Call the main question-answering function from the worker module [cite: 2]
        answers = await answer_queries(
            queries=[(q, document_id) for q in request.questions],
            services=services,
            semantic_weight=request.semantic_weight,
            keyword_weight=request.keyword_weight,
            k_semantic=request.k_semantic,
            k_keyword=request.k_keyword,
            k_rerank=request.k_rerank
        )
        print("✅ Q&A pipeline complete.")
        # [cite_start]Return the job ID and the generated answers [cite: 2]
        return {"job_id": document_id, "answers": answers}
    except Exception as e:
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=f"Failed to generate answers: {str(e)}")

@app.post('/analyze')
async def analyze_document(request: AnalyzeRequest):
    """
    Analyzes a sponsorship agreement for risky, ambiguous, or potentially harmful clauses.
    Ingests the document (if not already indexed), then runs legal risk detection using
    hybrid retrieval + reranking with specialized legal risk queries.
    """
    document_url = request.document
    document_id = generate_document_id(document_url)

    # --- STAGE 1: DOCUMENT PROCESSING & INDEXING ---
    await _ingest_document_if_needed(document_url, document_id)

    # --- STAGE 2: LEGAL RISK ANALYSIS ---
    try:
        print(f"⚖️ Starting legal risk detection pipeline...")
        risky_clauses = await analyze_legal_risks(
            document_id=document_id,
            services=services,
            semantic_weight=request.semantic_weight,
            keyword_weight=request.keyword_weight,
            k_semantic=request.k_semantic,
            k_keyword=request.k_keyword,
            k_rerank=request.k_rerank
        )
        print(f"✅ Legal risk analysis complete. Found {len(risky_clauses)} risky clauses.")

        high = sum(1 for c in risky_clauses if c.get("risk_level") == "high")
        medium = sum(1 for c in risky_clauses if c.get("risk_level") == "medium")
        low = sum(1 for c in risky_clauses if c.get("risk_level") == "low")

        response_data = AnalyzeResponse(
            document_id=document_id,
            total_risks_found=len(risky_clauses),
            high_risk_count=high,
            medium_risk_count=medium,
            low_risk_count=low,
            risky_clauses=[RiskyClause(**c) for c in risky_clauses]
        )

        if request.format == "text":
            return PlainTextResponse(content=format_risk_report(response_data))
        return response_data
    except Exception as e:
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=f"Failed to analyze document: {str(e)}")


@app.get('/')
def root():
    """A simple endpoint to confirm the API is live."""
    return {"message": "DeepRead AI - Legal Risk Detection API is live"}
